# Generated by Django 5.0.1 on 2024-04-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_qrcodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodes',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='qrcodes',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='qrcodes',
            name='qr_code_url',
            field=models.URLField(default='http://localhost:3000/attendance?class_id=1'),
            preserve_default=False,
        ),
    ]
