# Generated by Django 5.0.1 on 2024-02-11 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_course_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
