# Generated by Django 5.0.1 on 2024-02-11 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_class_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='university',
        ),
    ]
