# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
 
name: Build and deploy Node.js to Azure - c0027816-devproject-react

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '20.x' # It's recommended to use LTS version of Node.js

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build Next.js app
        run: |
          npm run build
          mv .next/static .next/standalone/.next/static
        working-directory: ./frontend

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./frontend/.next

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'c0027816-devproject-react'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_05DD5E63BDD24898B0D76B365E3487D6 }}
          package: ./frontend/.next/standalone 